### ISSUE TITLE
Add profiles to about page

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#192]
Work with mike to see which employees have had their profile sketches made but do not yet exist in the about page. Make the ones that don't exist in the about page.

**Comment by MissyM2** [comment]
OK, I will do that.
Missy
missymaloney1@gmail.com

**Comment by MissyM2** [comment]
Here is a list of those not on the website yet, with notes from Mike
fyi @omnipresent07 
- Marc Phillips: complete, needs to be uploaded
- Miles Reiter
- Rebecca Mancuso: rough sketch complet3ed
- Steven Godofsky
- James Villarreal
- Jean Alle
- Ongel Dasilva
- Dan Mutombo
- Jack Bevis: sending images
- Calvin Fernandes
- Bhargac Joshi
- Vasmi Priya Adipoodi
- Missy Maloney: complete, needs to be uploaded
- Austine Luyegu

**Comment by omnipresent07** [comment]
@MissyM2 Lets upload the ones that are complete along with profile text. Reach out to people for their profile text.

**Comment by MissyM2** [comment]
Ok, Mike has a new one finished.  I will get the 3 new ones uploaded.

**Comment by MissyM2** [comment]
Uploaded and has text:
- Marc Phillips
- Rebecca Mancuso
- Jack Bevis
- Missy Maloney
- Paul Otto

Needs to be completed:
- Miles Reiter
- Steven Godofsky
- James Villarreal
- Jean Alle
- Ongel Dasilva
- Dan Mutombo
- Calvin Fernandes
- Bhargac Joshi
- Vasmi Priya Adipoodi
- Austine Luyegu

**Comment by turbomarc** [comment]
Please add the following with the placeholder image (illustrations coming later):

Dmitri Knapp
Sr. User Researcher/Designer

Dmitri is a user researcher and visual designer with over five years of designing enjoyable experiences in a variety of industries. Dmitri’s years of consumer interactions, business acumen, and user centered design provides a diverse perspective for complex design solutions that have a wide range of stakeholders. Dmitri loves exploring user inclusivity and finding solutions that are both sustainable, ethical, and accessible. Dmitri spends the majority of his time in Figma or Miro, streamlining team processes or exploring new user flows for better experience design. Outside of user centered design, Dmitri enjoys video games, renovating houses and creating art.

Linkedin: https://www.linkedin.com/in/dmitriknapp/
Github: https://github.com/dk-ui
Website: http://www.dmitriknapp.com/



Aaron Beavers
Full Stack Developer

Aaron is a Full Stack Engineer, who got his started creating 3d models with tools like 3ds max and ZBrush for video games. He got bored, and started writing code for games, and managed to continue to find enough new material he didn't get bored with it. Now he is a software generalist, casting a wide net, with a particular interest in artificial intelligence and the notion of emulating thought in a machine, to create user experience capable of its own intuition. He is always seeking a challenge.

LinkedIn: https://www.linkedin.com/in/aaron-beavers-76b13aa7/
GitHub: https://github.com/riatzukiza

**Comment by turbomarc** [comment]
Please add Ryan and Nick.

Ryan Salcido
Bio
Ryan is a DevSecOps Engineer with experience working at the Naval Postgraduate School and Department of Defense as a Data Scientist. At the Department of Defense, he developed web applications using JavaScript, Vue.js, and Node.js as well as integrated continuous integration tools to improve the developer workflow in an AWS environment. Ryan is passionate about learning new technologies, creating user-friendly applications, and security. Outside of work, Ryan enjoys running and traveling.
 
Links
LinkedIn: https://www.linkedin.com/in/ryan-salcido/
GitHub: https://github.com/ryansalcido

===

Nick Grippin
Bio
Nick is a software engineer with a love of large-scale data problems.  Since graduating from Virginia Tech with a Bachelor's degree in Computer Science, he's spent his time building out streaming, asynchronous applications for both the government and private sector.  He loves finding ways to update outdated processes with new architecture and technology.  When not in front of the computer, Nick enjoys spending his time hiking, on his motorcycle, or playing a wide variety of tabletop games.

Links
LinkedIn: https://www.linkedin.com/in/nicholas-grippin-59354756

**Comment by MissyM2** [comment]
I am going to close this issue and open a new one for each of the upcoming changes to the About Page.
