### ISSUE TITLE
Typewriter animation intro headers on each page

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/raft-tech.github.io#458]
### but a [bit smoother like here]([like the attachment ](https://www.palantir.com/)

https://github.com/raft-tech/raft-tech.github.io/assets/106103383/c8a594f0-ec3f-4ce5-b56b-dff305654bd9

)

**Comment by benmarte** [comment]
Unfortunately, I'm not doing this for a number of reasons.

- Performance, using a js lib for this increases our file size footprint not to mention accessibility 
- It causes layout shifts since our text spans multiple lines
- CSS version does not work with multiple lines of text
- We will lose the ability to have different colors of text in the same sentence.
