### ISSUE TITLE
Image for articles on LinkedIn

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#49]
When posting articles on Linkedin, it is picking up the default Raft logo as the embedded image for the article rather than picking up the `featimg`.

**Comment by meissadia** [comment]
#52 might have fixed the issue on some blog posts, but we're still seeing it happen on others.
<img width="556" alt="Screen Shot 2020-02-25 at 10 39 21 AM" src="https://user-images.githubusercontent.com/2592907/75290691-11ba4e00-57de-11ea-8f51-7c60c48f9d39.png">
<img width="553" alt="Screen Shot 2020-02-25 at 10 43 43 AM" src="https://user-images.githubusercontent.com/2592907/75290722-20086a00-57de-11ea-845b-422b7f0ab890.png">

## LinkedIn guidelines for shareable content
https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en

No obvious violations of the above requirements that would explain the differing behaviors.

## Possible explanation
I think the [Principles](https://goraft.tech/2020/02/19/engineering-principles.html) post was initially shared with the Raft logo and later reposted with a different header image.  I wonder if LinkedIn does some caching of the `og:image` content that it pulls automatically.   That could explain why creating a new LinkedIn posting for an older blog post displays the correct header image, while a new LinkedIn post for a blog post that was posted recently on LinkedIn still reflects the now outdated `og:image`.  

## Next steps
Going to keep this issue open and see what happens with the next blog post shared to social media.  If LinkedIn is able to automatically populate the correct image, will re-close this ticket.  Otherwise, can do some more investigation into potential causes.

**Comment by meissadia** [comment]
Looks like this is working correctly for new posts.
<img width="555" alt="Screen Shot 2020-03-07 at 1 38 17 PM" src="https://user-images.githubusercontent.com/2592907/76280125-7e116480-6256-11ea-9d71-c0b0f19106cb.png">
