### ISSUE TITLE
Some blog posts are not mobile responsive

### ISSUE THREAD

**Issue by omnipresent07** [raft-tech/raft-tech.github.io#50]
<img width="409" alt="Screen Shot 2020-02-20 at 10 13 29 AM" src="https://user-images.githubusercontent.com/44377678/74948007-acbfbc00-53c9-11ea-8c00-3082bb065788.png">

**Comment by meissadia** [comment]
Notes:

Main Issue - Long URLs in the References section at the bottom of the page.  
Fix - Will replace URLs with the referenced page titles so that the text can wrap

Other Issues:
- Misspelled 'Refrences'
- Ref #1 is a dead link
- Ref #2, #4 don't display unless opened in new tab.  (Make all ref links open in new tab?)
- [ ] Check other blog posts for similar issues

**Comment by meissadia** [comment]
- Ref `#1` is not a dead link
- Ref `#2, #4` seem to be loading fine in the same window, not sure what was happening earlier.
- No side scrolling issues on other blog posts.
